"""Week 3 baseline: run the agent on the 5 test tasks and record the outputs.

Each test task is a résumé fixture in ``tests/fixtures``. For each, the agent runs
its search→score→decide→refine loop against live Remotive + Claude and we capture
the ranked matches. Results are printed and written to ``docs/baseline_outputs.md``.

Run:  python scripts/run_baseline.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from dotenv import load_dotenv  # noqa: E402

from job_scout.agent import AgentResult, run_agent  # noqa: E402
from job_scout.resume import load_resume  # noqa: E402

load_dotenv()

FIXTURES = ROOT / "tests" / "fixtures"
OUTPUT = ROOT / "docs" / "baseline_outputs.md"
TOP_N = 5


def run_one(path: Path) -> AgentResult:
    resume_text = load_resume(path)
    return run_agent(
        resume_text,
        resume_label=path.stem,
        db_path=None,  # keep test runs isolated from the real SQLite state
        alert_threshold=9.0,
        good_threshold=7.0,
        target_good=3,
        max_rounds=2,        # keep the baseline fast / cheap
        jobs_per_round=6,
        claude_path=os.environ.get("CLAUDE_PATH"),
        home=os.environ.get("CLAUDE_HOME"),
        model=os.environ.get("JOB_SCOUT_MODEL") or None,
    )


def render(result: AgentResult) -> str:
    lines = [f"## Task: `{result.resume_label}`", ""]
    rounds = ", ".join(
        f"'{r.query}' → {r.n_jobs} jobs / {r.n_good} good [{r.scorer}]"
        for r in result.rounds
    )
    lines.append(f"- **Rounds:** {rounds}")
    lines.append(f"- **Tried queries:** {', '.join(result.tried_queries)}")
    lines.append(f"- **Postings seen:** {len(result.scored)}")
    lines.append(f"- **Alert-worthy (>= 9):** {len(result.alerts)}")
    lines.append("")
    lines.append("| Score | Title | Company | Scorer | Why |")
    lines.append("|------:|-------|---------|--------|-----|")
    for s in result.scored[:TOP_N]:
        why = (s.reasoning or "").replace("|", "/")[:90]
        title = s.job.title.replace("|", "/")[:50]
        company = s.job.company.replace("|", "/")[:30]
        lines.append(f"| {s.score:.1f} | {title} | {company} | {s.source} | {why} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    fixtures = sorted(FIXTURES.glob("resume_*.md"))
    if not fixtures:
        print(f"No fixtures found in {FIXTURES}", file=sys.stderr)
        return 1

    print(f"Running baseline on {len(fixtures)} test tasks...\n")
    sections = [
        "# Week 3 Baseline Outputs",
        "",
        "Generated by `scripts/run_baseline.py`. The agent ran its "
        "search→score→decide→refine loop on each résumé fixture against a live "
        "multi-source job corpus (RemoteOK + Remotive) scored by Claude. "
        "`Scorer` shows whether Claude or the keyword fallback produced the score.",
        "",
    ]
    for path in fixtures:
        print(f"=== {path.stem} ===")
        result = run_one(path)
        for s in result.scored[:TOP_N]:
            print(f"  {s.score:4.1f}  {s.job.title[:55]:55}  [{s.source}]")
        print(f"  tried: {', '.join(result.tried_queries)}\n")
        sections.append(render(result))

    OUTPUT.write_text("\n".join(sections), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
